import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
} from 'typeorm';

/**
 * Abstract base entity providing common audit fields for all domain entities.
 *
 * All concrete entities should extend this class to inherit `id`, `createdAt`,
 * `updatedAt`, and `deletedAt` mapped columns. The `@Entity` decorator must be
 * applied on the concrete subclass — this class intentionally has no `@Entity`
 * decorator so it acts purely as a mapped-superclass.
 */
export abstract class BaseEntity {
  /**
   * Universally unique identifier generated by the database.
   */
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /**
   * Timestamp of record creation, set automatically by TypeORM.
   */
  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;

  /**
   * Timestamp of the last update, maintained automatically by TypeORM.
   */
  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;

  /**
   * Soft-delete timestamp. When set, the record is considered deleted
   * and will be excluded from standard queries.
   */
  @DeleteDateColumn({ name: 'deleted_at', nullable: true })
  deletedAt?: Date;
}
